/**
 * exportReport.ts
 * ------------------------------------------------------------------
 * Drop this file into: src/utils/exportReport.ts
 *
 * Zero dependencies — uses only the built-in Blob/URL APIs already
 * available in every browser, so it cannot introduce an install error.
 * ------------------------------------------------------------------
 */

export interface AlertLogEntry {
  id: string;
  timestamp: string; // ISO string
  zoneName: string;
  densityPercent: number;
  channel: "SMS" | "CALL";
  recipient: string;
  status: "sent" | "simulated" | "failed";
  twilioSid?: string;
}

function escapeCsvField(value: string | number): string {
  const str = String(value);
  if (str.includes(",") || str.includes('"') || str.includes("\n")) {
    return `"${str.replace(/"/g, '""')}"`;
  }
  return str;
}

function downloadBlob(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const link = document.createElement("a");
  link.href = url;
  link.download = filename;
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
  URL.revokeObjectURL(url);
}

/**
 * Exports the alert history log as a CSV file the browser downloads
 * immediately. Call this from a button's onClick handler.
 */
export function exportAlertLogCSV(entries: AlertLogEntry[], filename = "crowdguardian-incident-report.csv") {
  const headers = ["Timestamp", "Zone", "Density %", "Channel", "Recipient", "Status", "Twilio SID"];
  const rows = entries.map((e) =>
    [
      e.timestamp,
      e.zoneName,
      e.densityPercent,
      e.channel,
      e.recipient,
      e.status,
      e.twilioSid ?? "",
    ]
      .map(escapeCsvField)
      .join(",")
  );

  const csv = [headers.join(","), ...rows].join("\n");
  downloadBlob(csv, filename, "text/csv;charset=utf-8;");
}

/**
 * Exports a plain-text incident summary report — handy for a quick
 * "print this for the judges" artifact alongside the CSV.
 */
export function exportIncidentSummaryTXT(
  entries: AlertLogEntry[],
  meta: { generatedBy?: string; venueName?: string } = {},
  filename = "crowdguardian-incident-summary.txt"
) {
  const lines: string[] = [];
  lines.push(`CrowdGuardian AI — Incident Summary Report`);
  lines.push(`Venue: ${meta.venueName ?? "N/A"}`);
  lines.push(`Generated: ${new Date().toLocaleString()}`);
  lines.push(`Generated by: ${meta.generatedBy ?? "Command Center Operator"}`);
  lines.push("");
  lines.push(`Total alerts: ${entries.length}`);
  lines.push("--------------------------------------------------");

  entries.forEach((e, i) => {
    lines.push(
      `${i + 1}. [${e.timestamp}] ${e.zoneName} — ${e.densityPercent}% density — ${e.channel} to ${e.recipient} (${e.status})${
        e.twilioSid ? ` SID:${e.twilioSid}` : ""
      }`
    );
  });

  downloadBlob(lines.join("\n"), filename, "text/plain;charset=utf-8;");
}
